version: 2.1

orbs:
  ci: bigcommerce/internal@volatile
  php: bigcommerce/internal-php@volatile

workflows:
  version: 2
  full:
    jobs:
      - php/phpunit-tests:
          configuration: "phpunit.xml.dist"
          matrix:
            parameters:
              php-version: [ "8.0", "8.1", "8.2" ]
